name: build native libraries
on:
  workflow_dispatch:    # allow to manually trigger this workflow
  push:
    branches:
      - michael/github-actions-debug
jobs:
  natives:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - run: gradle buildNatives
      - name: Upload decompiler
        uses: actions/upload-artifact@v4
        with:
          path: Ghidra/Features/Decompiler/build/os/*
          if-no-files-found: error
