name: release
on:
  workflow_dispatch:    # allow to manually trigger this workflow
  push:
    branches:
      - michael/github-actions-debug
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - name: Display structure of downloaded files
        run: ls -R
